### ISSUE TITLE
Users table에서 point 컬럼 임시 삭제

### ISSUE THREAD

**Issue by hysy9255** [wecode-bootcamp-korea/40-1st-weKea-backend#5]
Users table에서 point 컬럼을 임시적으로 삭제하였음. 

회원가입 시 point가 자동으로 할당되는 로직을 만들어야함. 이 로직이 아직 구현되지 않아 migration file에서 임시적으로 빼 놓았음.

**Comment by gkgkda** [comment]
확인했습니다.
